### ISSUE TITLE
Embeded help response

### ISSUE THREAD

**Issue by SystematicError** [astariul/discord_interactive_help#14]
Hey, I **_LOVE_** this project however is there any way to do this in an embed? My bot responds in embeds and it will be great if the help command will also be a embed.

Thanks, SystematicError

**Comment by ghost** [comment]
That's a great idea ! 

To be honest so far I didn't know there is such a thing as `Embed` 😅 

---

Do you feel confident opening a PR ?  
That would be the first PR of this project ! I can help for sure.

---

As a side note, it might actually be a good idea to **always** return help manual as `Embed`. It seems cleaner, more "interface-like" than a normal message.  
Or at least make the `Embed` as the default way to do it. What do you think ?

**Comment by SystematicError** [comment]
Hey, thanks for the response

I am pretty sure you might have seen an embed, just not know its name. Anyways here is what an embed will look like: [Embed Image](https://images.app.goo.gl/ReYkp2ENPui1Eshp9)

Here is some basic code:
```python
msg = discord.Embed(title = 'My own Embed!', description = 'Hello World!' color=0xE67E22)
await ctx.send(embed = msg, content = None)
```
This will create an embed with an orange color I believe.

**Comment by ghost** [comment]
Keeping open for now. The `master` have all the change to be working, but wiki is not updated yet.

Also, I would like the feedback of @SystematicError to see if it's what was expected :)

Since there is no documentation yet, you can check the source code, or the main example.

Basically now all `Pages` are using Embed. You can pass `Embed` constructor parameters in the `Page` constructor.

```python
p = Page("Description of my page")       # A page like before. Is now rendered as Embed by default
p = Page("Description of my page", title="My title")        # A title :)
p = Page("Description of my page", color=0xE67E22)       # A color :D
```

---

Don't forget to update your package with `pip install --upgrade discord-interactive`
