### ISSUE TITLE
🚀 Use edit instead of deleting

### ISSUE THREAD

**Issue by sairam4123** [astariul/discord_interactive_help#18]
## 🚀 Feature

Use editing instead of deleting, so there will be only 1 message, and the discord.py edits instead of deleting and resending the message.

## Motivation / Goal
Edit the message instead of deleting it, it takes 2 API calls, but editing a message takes only 1 API call, which is better.
So, I recommended using edit instead of deleting and resending,

I'll make a PR for this. When I have sometime.

**Comment by ghost** [comment]
Thanks for opening the issue !

Would love a PR :D

---

As far as I remember, I had some issue with editing a message instead of deleting + sending again. I don't remember the exact reason, I need to do more tests

**Comment by ghost** [comment]
The [Discord API for the `edit()` function](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.edit) does not offer interface for editing the reactions of the message.

There is a method [`remove_reaction()`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.remove_reaction), but from my trials, I couldn't make it work...

Also the biggest bottleneck in terms of time needed to display the message is adding the reactions, because reactions are added one by one... If we should also remove the reactions one by one, it will likely take a lot of time. Maybe faster to just delete and recreate the message.

---

**Anyway I would love to have another person looking at the code ! If you find anything, I would love a PR :)**

---

### What I tried so far

I changed this :

https://github.com/astariul/discord_interactive_help/blob/38249a5660f7c7e8987c2633911a36c32c994e81/discord_interactive/help.py#L65-L70

So we send a message if no message was sent, otherwise we [edit](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.edit) its content.

Then change this :

https://github.com/astariul/discord_interactive_help/blob/38249a5660f7c7e8987c2633911a36c32c994e81/discord_interactive/help.py#L104

and instead of deleting the message, I loop through the reactions of the message and delete every reactions (because reactions of the next message are likely to be differents) :

```python
for react in bot_message.reactions:
    asyncio.ensure_future(bot_message.remove_reaction(react, self.client.user))
```

**Comment by sairam4123** [comment]
Thanks, I'll do a PR later. I don't have time right now.

**Comment by sairam4123** [comment]
And Check this out too:
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.clear_reactions
It clears all reactions. 
So, you don't have to remove reactions your self.
